version: '3.8'

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_server
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP 标准端口
      - "443:443"    # HTTPS 标准端口
    environment:
      - NODE_ENV=production
      - HTTP_PORT=80
      - HTTPS_PORT=443
    volumes:
      # 持久化数据库
      - ./data:/app/database.db:Z
      # 持久化上传文件
      - ./uploads:/app/server/uploads:Z
      # 持久化临时文件
      - ./temps:/app/server/temps:Z
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加 Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: api_server_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api-server
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  api-data:
    driver: local
