"use strict";
// Barrel file — re-exports all HTTP controller modules
// Original 1311-line httpController.ts has been split into:
//   fileController.ts, httpBaseController.ts, payloadController.ts, httpTestController.ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.postForm = exports.postJson = exports.head_basic = exports.options_basic = exports.patch_basic = exports.delete_basic = exports.put_basic = exports.post_basic = exports.get_basic = exports.get8M = exports.get4M = exports.get2M = exports.get1M = exports.get8K = exports.get4K = exports.get2K = exports.get1K = exports.getPayload = exports.getEchoHeaders = exports.getHeaders = exports.getDelay = exports.getStatusCode = exports.getParams = exports.getQuery = exports.getDefault = exports.saveJsonFile = exports.readJsonFile = exports.listJsonFiles = exports.put_file = exports.downloadFile = exports.uploadFile = exports.deleteFile = exports.getFiles = void 0;
var fileController_1 = require("./fileController");
Object.defineProperty(exports, "getFiles", { enumerable: true, get: function () { return fileController_1.getFiles; } });
Object.defineProperty(exports, "deleteFile", { enumerable: true, get: function () { return fileController_1.deleteFile; } });
Object.defineProperty(exports, "uploadFile", { enumerable: true, get: function () { return fileController_1.uploadFile; } });
Object.defineProperty(exports, "downloadFile", { enumerable: true, get: function () { return fileController_1.downloadFile; } });
Object.defineProperty(exports, "put_file", { enumerable: true, get: function () { return fileController_1.put_file; } });
Object.defineProperty(exports, "listJsonFiles", { enumerable: true, get: function () { return fileController_1.listJsonFiles; } });
Object.defineProperty(exports, "readJsonFile", { enumerable: true, get: function () { return fileController_1.readJsonFile; } });
Object.defineProperty(exports, "saveJsonFile", { enumerable: true, get: function () { return fileController_1.saveJsonFile; } });
var httpBaseController_1 = require("./httpBaseController");
Object.defineProperty(exports, "getDefault", { enumerable: true, get: function () { return httpBaseController_1.getDefault; } });
Object.defineProperty(exports, "getQuery", { enumerable: true, get: function () { return httpBaseController_1.getQuery; } });
Object.defineProperty(exports, "getParams", { enumerable: true, get: function () { return httpBaseController_1.getParams; } });
Object.defineProperty(exports, "getStatusCode", { enumerable: true, get: function () { return httpBaseController_1.getStatusCode; } });
Object.defineProperty(exports, "getDelay", { enumerable: true, get: function () { return httpBaseController_1.getDelay; } });
Object.defineProperty(exports, "getHeaders", { enumerable: true, get: function () { return httpBaseController_1.getHeaders; } });
Object.defineProperty(exports, "getEchoHeaders", { enumerable: true, get: function () { return httpBaseController_1.getEchoHeaders; } });
var payloadController_1 = require("./payloadController");
Object.defineProperty(exports, "getPayload", { enumerable: true, get: function () { return payloadController_1.getPayload; } });
Object.defineProperty(exports, "get1K", { enumerable: true, get: function () { return payloadController_1.get1K; } });
Object.defineProperty(exports, "get2K", { enumerable: true, get: function () { return payloadController_1.get2K; } });
Object.defineProperty(exports, "get4K", { enumerable: true, get: function () { return payloadController_1.get4K; } });
Object.defineProperty(exports, "get8K", { enumerable: true, get: function () { return payloadController_1.get8K; } });
Object.defineProperty(exports, "get1M", { enumerable: true, get: function () { return payloadController_1.get1M; } });
Object.defineProperty(exports, "get2M", { enumerable: true, get: function () { return payloadController_1.get2M; } });
Object.defineProperty(exports, "get4M", { enumerable: true, get: function () { return payloadController_1.get4M; } });
Object.defineProperty(exports, "get8M", { enumerable: true, get: function () { return payloadController_1.get8M; } });
var httpTestController_1 = require("./httpTestController");
Object.defineProperty(exports, "get_basic", { enumerable: true, get: function () { return httpTestController_1.get_basic; } });
Object.defineProperty(exports, "post_basic", { enumerable: true, get: function () { return httpTestController_1.post_basic; } });
Object.defineProperty(exports, "put_basic", { enumerable: true, get: function () { return httpTestController_1.put_basic; } });
Object.defineProperty(exports, "delete_basic", { enumerable: true, get: function () { return httpTestController_1.delete_basic; } });
Object.defineProperty(exports, "patch_basic", { enumerable: true, get: function () { return httpTestController_1.patch_basic; } });
Object.defineProperty(exports, "options_basic", { enumerable: true, get: function () { return httpTestController_1.options_basic; } });
Object.defineProperty(exports, "head_basic", { enumerable: true, get: function () { return httpTestController_1.head_basic; } });
Object.defineProperty(exports, "postJson", { enumerable: true, get: function () { return httpTestController_1.postJson; } });
Object.defineProperty(exports, "postForm", { enumerable: true, get: function () { return httpTestController_1.postForm; } });
