name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # 1. 检出代码
      - uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # 缓存 npm 依赖

      # 3. 安装依赖
      - name: Install dependencies
        run: npm ci

      # 4. 构建项目
      - name: Build project
        run: npm run build --if-present

      # 5. 运行测试并生成覆盖率报告
      - name: Run tests
        run: npm test --if-present
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # 需要配置 Codecov token

      # 6. 安全性检查
      # - name: Run npm audit
      #   run: npm audit

      # 7. 启动服务器并运行 API 测试（可选）
      - name: Start server
        run: npm run start &
        env:
          PORT: 3000  # 设置环境变量（如果需要）

      # 8. 部署到 GitHub Pages（可选）
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # 假设构建输出在 dist 目录
